const express = require('express');
const adverts = require('../controllers/adverts');
const auth = require('../controllers/auth');
const route = express.Router();
route.get('/',adverts.index);
route.get('/:id',adverts.view);
route.post('/', auth.verifyToken,adverts.create);
route.put('/:id',auth.verifyToken,adverts.update);
route.delete('/:id/:image', auth.verifyToken,adverts.delete);
module.exports = route;
