const express = require('express');
const reviews = require('../controllers/reviews');
const auth = require('../controllers/auth');
const route = express.Router();
route.get('/',reviews.index);
route.get('/:id',reviews.view);
route.post('/', auth.verifyToken,reviews.create);
route.post('/upload', auth.verifyToken,reviews.upload);
route.put('/:id',auth.verifyToken,reviews.update);
route.delete('/:id/:image', auth.verifyToken, reviews.delete);
route.delete('/:id', auth.verifyToken,reviews.delete);
module.exports = route;
